django_delights/django_delights/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('inventory.urls'))
]

django_delights/inventory/urls.py
from django.urls import path, include
from . import views

urlpatterns=[
    path('', views.home, name="home"),
    path("ingredient/all/", views.IngredientsList.as_view(), name="ingredients"),
    path("ingredient/<int:ingred_id>/delete/", views.delete_ingredient, name="delete_ingredient"),
    path("menu/all items/", views.MenuItemsList.as_view(), name="menu_items"),
    path("ingredient/<int:menu_id>/delete/", views.delete_menu_item, name="delete_menu_item"),
    path("purchases/all/", views.PurchasesList.as_view(), name="purchases"),
    path("menu/new item", views.NewMenuItem.as_view(), name="new_menu_item")
]

django_delights/inventory/models.py
from django.db import models
import datetime
from django.utils import timezone
import calendar

# Create your models here.
class Ingredient(models.Model):
    name=models.CharField(max_length=200)
    quantity=models.DecimalField(default=0, max_digits=4, decimal_places=1)
    unit_price=models.DecimalField(max_digits=6, decimal_places=2)
    mililitre='mL';litre="L";teaspoon="tsp.";tablespoon="tbl.";fluid_ounce="fl oz"
    cup="c"; pint="p";gallon="gal";miligram="mg";gram="g";kilogram="kg"; pounds="lbs"
    ounce="oz"; whole_unit="unit"
    UNIT_CHOICES=[(mililitre, "Mililitre"), (litre, "Litre"), (teaspoon,"Teaspoon"),
    (tablespoon,"Tablespoon"),(fluid_ounce,"Fluid Ounce"), (cup, "Cup"), (pint, "Pint"),
    (gallon,"Gallon"),(miligram,"Miligram"), (gram,"Gram"),(kilogram, "Kilogran"),
    (pounds, "Pounds"),(ounce, "Ounce"), (whole_unit,"Individual Unit")]
    unit=models.CharField(max_length=5, choices=UNIT_CHOICES)

    class Meta:
        ordering=['name']

    def __str__(self):
        return f"{self.name}"
    
    def get_absolute_url(self):
        return "/ingredient/all"

class MenuItem(models.Model):
    title=models.CharField(max_length=200)
    price=models.DecimalField(max_digits=6, decimal_places=2)
    star_rating=models.IntegerField(default=3, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
    
    class Meta:
        ordering=['star_rating']
    def __str__(self):
        return f"{self.title}"
    
    def iterable_stars(self):
        return range(self.star_rating)

class RecipeRequirement(models.Model):
    menu_item=models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    ingredient=models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity=models.DecimalField(max_digits=4, default=0, decimal_places=1)

    

    def __str__(self):
        return f"{self.ingredient} for {self.menu_item}"

class Purchase(models.Model):
    menu_item=models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    timestamp=models.DateTimeField()

    def __str__(self):
        return f"{self.menu_item}: {self.timestamp}"

    def simplified_time(self):
        month=self.timestamp.month
        return self.timestamp.strftime(f"%d-{calendar.month_name[month]}-%Y")
    
    class Meta:
        ordering=["timestamp"]

django_delights/inventory/forms.py
from django import forms
from .models import Purchase, MenuItem, Ingredient, RecipeRequirement


#Create
class PurchaseCreateForm(forms.ModelForm):
    class Meta:
        model=Purchase
        fields=("menu_item", "timestamp")

class MenuItemCreateForm(forms.ModelForm):
    class Meta:
        model=MenuItem
        fields=('title', 'price', 'star_rating')


class RecipeRequirementCreateForm(forms.ModelForm):
    class Meta:
        model=RecipeRequirement
        fields=('menu_item', 'ingredient', 'quantity')

django_delights/inventory/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse
from django.views.generic import ListView, TemplateView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from . models import Ingredient, MenuItem, Purchase, RecipeRequirement
from django.urls import reverse_lazy
import itertools
from .forms import MenuItemCreateForm, PurchaseCreateForm


def home(request):
    return render(request, "inventory/index.html", panel_context())

def getRevenue(purchases):
    return round(sum([purchase.menu_item.price for purchase in purchases]),2)

def getCostPurchases(purchases):    
    extract = lambda items: [item.ingredient.unit_price* item.quantity for item in items]
    ingreds=[extract(purchase.menu_item.reciperequirement_set.all()) for purchase in purchases]
    return round(sum(list(itertools.chain(*ingreds))),2)

def panel_context():
    purchases= Purchase.objects.all() 
    recent_purchases=purchases.order_by('-timestamp')[:3]

    menuItems = MenuItem.objects.all()

    popular_items=[    
    {
        "item":item,
        "num_purchases":len(item.purchase_set.all())
    } 
    for item in menuItems][:5]
    popular_items.sort(key=lambda food: food['num_purchases'], reverse=True)
    
    
     
    cost = getCostPurchases(purchases)
    revenue=getRevenue(purchases)
    generic_info=[
        {"name":"Number of Purchases", "value":len(purchases)},
        {"name":"Operating Costs", "value":cost},
        {"name":"Proft", "value":round(revenue-cost,2)}
    ]
    context={"name": "Jude", "generic_info":generic_info, "purchases":purchases, "recent_purchases":recent_purchases, "popular_items":popular_items}
    return context

class PurchasesList(ListView):
    model=Purchase
    template_name="inventory/purchases.html"
    extra_context=panel_context()

class IngredientsList(ListView):
    model=Ingredient
    template_name= "inventory/ingredients.html"
    extra_context=panel_context()

class MenuItemsList(ListView):
    model=MenuItem
    template_name="inventory/menu.html"
    extra_context=panel_context()

def delete_ingredient(request, ingred_id):
    try:
        ingredient=Ingredient.objects.get(pk=ingred_id)
    except Ingredient.DoesNotExist:
        raise Http404("Ingredient does not exist")
    else:
        ingredient.delete()
        return redirect("ingredients")

def delete_menu_item(menu_id):
    try:
        menu_item=MenuItem.objects.get(pk=menu_id)
    except MenuItem.DoesNotExist:
        raise Http404("Menu item does not exist")
    else: 
        menu_item.delete()
        return redirect('menu_items')

class NewMenuItem(CreateView):
    model=MenuItem
    template_name="forms/new_menu_item.html"
    form_class = MenuItemCreateForm
    extra_context=panel_context()

django_delights/inventory/templates/forms/new_menu_item.html
{% extends '../inventory/base.html' %}

{% block content %}
<h2>New Menu item</h2>
<form method="post">
    <div>{% csrf_token %} {{form.as_p}}</div>
    <input type="submit" value="Submit">
</form>
{% endblock %}

django_delights/inventory/templates/inventory/base.html
<head>
    
    
    {% block head %}
    {% endblock %}
    
    <title>
        Django Restaurant Inventory
    </title>
</head> 
<body>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'inventory/base.css' %}">
   <div class="blocks">
        <div class="side_panel">
            <header>
                <a href="{% url 'home'%}"><h1>Inventory</h1></a>
                <a href="{% url 'ingredients' %}">Ingredients</a>
                <a href="{% url 'menu_items' %}">Menu Items</a>
                <a href="{% url 'purchases' %}">Purchases</a>
            </header>
        </div>
       <div class="content">
            {% for x in generic_info %}
            {{x.name}}: {{x.value}}
            {% endfor %}


           {% block content %}
           {% endblock %}
       </div>
       <div class="side_panel">
          {% for p in recent_purchases %}
          <div class="purchase_item">
              <img src="{%static 'tick.jpg'%}" class="purchases-tick" alt="">
              <p>{{p.menu_item}}</p>
              <p>{{p.menu_item.price}}</p>
              <p>{{p.simplified_time}}</p>
          </div>
          {% endfor %}
       </div>
   </div>

</body>

django_delights/inventory/templates/inventory/index.html
{% extends "inventory/base.html" %}

{% block content %}
<br>
<br>
<br>
<div>
    {{popular_items}}
</div>

{% for item in menu %}
hi
{% endfor %}

{% endblock %}
{% block right_panel %}
<table>
    <tr>
        <th>Number of purchases</th>
        <th>Cost</th>
        <th>Revenue</th>
        <th>Profit</th>
    </tr>
    <tr>
        <td>{{purchases|length}}</td>
        <td>£{{cost}}</td>
        <td>£{{revenue}}</td>
        <td>£{{profit}}</td>
    </tr>
</table>
{% endblock %}

django_delights/inventory/templates/inventory/ingredients.html
{% extends 'inventory/base.html' %}
{% block content %}

<h2>Ingredients</h2>
<table id="ingredients-table">
    <tr>
        <th>Ingredient</th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Price</th>
        <th>Modify</th>
    </tr>
    {% for ingred in ingredient_list %}
    <tr>
        <td>{{ ingred.name }}</td>
        <td>{{ ingred.quantity }}</td>
        <td>{{ ingred.unit }}</td>
        <td>{{ ingred.unit_price }}</td>
        <td>
        <form action="{% url 'delete_ingredient' ingred.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Delete">
        </form>
            <!-- <a href="{% url 'delete_ingredient' ingred.id %}"><button>Delete Old - Dont use</button>
            </a> -->
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

django_delights/inventory/templates/inventory/menu.html
{% extends 'inventory/base.html' %}
{% block content %}

<h2>Menu Items</h2>
<table id="menu-table">
    <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Stars</th>
        <th>Modify</th>
    </tr>
    {% for item in menuitem_list %}
    <tr>
        <td>{{ item.title }}</td>
        <td>{{ item.price }}</td>
        <td>{% for star in item.iterable_stars %}*{% endfor %}
        </td>
        <td>
        <form action="{% url 'delete_menu_item' item.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Delete">
        </form>
            
        </td>
    </tr>
    {% endfor %}
    <a href="{% url 'new_menu_item' %}">New Item</a>
</table>

{% endblock %}

django_delights/inventory/templates/inventory/purchases.html
{% extends 'inventory/base.html' %}

{% block content %}
<h2>Purchases</h2>

<table id="purchases-table">
    <tr>
        <th>Item</th>
        <th>Time</th>
    </tr>
    {% for x in purchase_list %}
    <tr>
        <td>
            {{x.menu_item}}
        </td>
        <td>
            {{x.simplified_time}}
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}